### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'original_state_dict'

### ISSUE THREAD

**Issue by vantienpham** [fractalego/laser-svd#1]
Hi, thank you for your repository.
When I run the code, it says:
```
python substitute_layers_above_and_generate_short_sentences.py 
/home/van-tien.pham/laser-svd/src/substitute_layers_above_and_generate_short_sentences.py:105: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  new_model_state_dict = filter_layers(torch.load("mistral-7b-instruct-laser-distil-backward-0.5"), lowest_threshold_layer)
/home/van-tien.pham/laser-svd/src/substitute_layers_above_and_generate_short_sentences.py:106: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  original_model_state_dict = torch.load("original_state_dict")
Traceback (most recent call last):
  File "/home/van-tien.pham/laser-svd/src/substitute_layers_above_and_generate_short_sentences.py", line 106, in <module>
    original_model_state_dict = torch.load("original_state_dict")
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van-tien.pham/anaconda3/envs/laser/lib/python3.12/site-packages/torch/serialization.py", line 1065, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van-tien.pham/anaconda3/envs/laser/lib/python3.12/site-packages/torch/serialization.py", line 468, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van-tien.pham/anaconda3/envs/laser/lib/python3.12/site-packages/torch/serialization.py", line 449, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'original_state_dict'
```

How can I have this file? 
Thank you in advance for your help!

**Comment by fractalego** [comment]
Hi!
That is the original Mistral state dictionary. I believe this is how I saved it.

```python
import torch
from transformers import AutoModelForCausalLM

model_name = "mistralai/Mistral-7B-Instruct-v0.1"
model = AutoModelForCausalLM.from_pretrained(model_name)
torch.save(model.state_dict(), "original_state_dict")
```

That's on me: This is more of a weekend project and could not upload everything.

**Comment by vantienpham** [comment]
Thank you, it works.
